name: Pipeline CI/CD ESGInteligentes

on:
  push:
    branches: [ "main" ] # O pipeline roda sempre que você envia código

jobs:
  # ETAPA 1: BUILD (CONSTRUÇÃO)
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build da Imagem Docker
        [cite_start]run: docker build -t esg-app:latest . [cite: 12]

  # ETAPA 2: TESTE
  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Instalar Dependências
        run: pip install -r requirements.txt
      - name: Executar Testes de Conexão
        [cite_start]run: python src/app.py # Simula o teste rodando a aplicação [cite: 13]

  # ETAPA 3: DEPLOY (IMPLANTAÇÃO)
  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Deploy em Staging
        [cite_start]run: echo "Efetuando deploy no ambiente de STAGING..." [cite: 14]
      - name: Deploy em Produção
        [cite_start]run: echo "Efetuando deploy no ambiente de PRODUÇÃO..." [cite: 14]
